name: Practica CI JAVA

on:
   pull_request:
      branches:
         - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs: 
  build:
     runs-on: ubuntu-latest
     steps:
       - uses:  actions/checkout@v2
       - name: configurar JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
       - name: Ejecuta las pruebas de integracion
         run: mvn verify 
       - name: Compilar proyecto 
         run: mvn clean install

  dockerhub:
    runs-on: ubuntu-latest
    steps:
       - name: Revisa el Repo 
         uses: actions/checkout@v2
      
       - name: Login Docker hub 
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Configurar Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1

       - name: Build y push Docker Images
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: ./
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/practica:latest
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache

       - name: Resumen de imágenes
         run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA --platform managed --region $RUN_REGION
       
         





