name: Practica CI JAVA

on:
   pull_request:
      branches:
         - master

jobs: 
  build:
     runs-on: ubuntu-latest
     steps:
       - uses:  actions/checkout@v2
       - name: configurar JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
       - name: Ejecuta las pruebas de integracion
         run: mvn verify 
       - name: Compilar proyecto 
         run: mvn clean install

  deploy:
     name: Deploy to cluster
     runs-on: ubuntu-latest
     steps:
       - uses:  actions/checkout@master
       - name: Construir y subir a Docker hub 
         uses: docker/build-push-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: ${{ github.repository }}
           tag_with_ref: true
           tag_with_sha: true
           tags: ${{ github.sha }}
       
         





