name: Practica CI JAVA

on:
   pull_request:
      branches:
         - master

jobs: 
  build:
     runs-on: ubuntu-latest
     steps:
       - uses:  actions/checkout@v2
       - name: configurar JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
       - name: Ejecuta las pruebas de integracion
         run: mvn verify 

   publish:
      name: Publicar paquete
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v2
         - name: Configurar el Repositorio 
           uses: actions/setup-java@v2
           with:
              java-version: '11'
              distribution: 'adopt'
              server-id: github
           run: mvn deploy -Dtoken=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


           


