name: Publicar JAVA

on:
   pull_request:
      branches:
         - master

jobs: 
 publish:
      name: Publicar paquete
      runs-on: ubuntu-latest
      steps: 
         - uses: actions/checkout@v2
         - name: Configurar el Repositorio 
           uses: actions/setup-java@v2
           with:
              java-version: '11'
              distribution: 'adopt'
              server-id: github
           run: mvn deploy -Dtoken=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
